[build]
  command = "npm install && npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_version = "20"
  external_node_modules = ["@prisma/client", "nodemailer"]
